---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - При просмотре товаров, вся информация должна быть видна в карточке товара и не выходить за ее пределы
  - Отображение уведомления, при добавлении товара в корзину
  - Выравнивание текста как предполагает дизайн
  - Кнопка оформления заказа
  - Переход на страницу оплаты после оформления заказа
  - Просмотр статуса заказа после оформления
  - Автоматическое очищение корзины после оформления заказа
  - Информация о количестве остатков товара не должна путать покупателя
  - Должна быть доступна фильтрация по рейтингу
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге, корзина хранится в сессии браузера
  - SPA-приложение, которое не перезагружает страницу. Пользователь будет просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
