---
- summary: |
    Данные о заказе не отправляются на сервер
  environment: |
    Google Chrome   130.0.6723.70 (Официальная сборка), (64 бит)
    ОС Windows 11 Pro 23H2
  steps-to-reproduce: |
    1. Нажимаем кнопку «checkout»
    2. Просматриваем заказ
    3. Данные о заказе отправляются на сервер
  expected-result: |
    Пользователь проверяет заказ
    Данные отправляются на сервер
  actual-result: |
    Пользователь проверяет заказ
    Данные не отправляются на сервер
    Выдает серверную ошибку
